apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: orc4n1hdz-go
  janus-idp.io/tekton: orc4n1hdz-go
  backstage.io/kubernetes-id: orc4n1hdz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: orc4n1hdz-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
