apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: orc4n1hdz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: orc4n1hdz-go 
  name: orc4n1hdz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: orc4n1hdz-go 
